version: '3.8'
name: master_thesis_graphs_hypergraphs

services:
  api:
    container_name: graph-api
    build: ./graph-api
    ports:
      - "8000:8000"
    volumes:
      - ./graph-api:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1